<?php
session_start();
        if(!isset($_SESSION["adminname"]))
		{
		 header( "location:admin.php" );
		}
		
	$date="";
        if ($_SERVER["REQUEST_METHOD"] == "POST")
			{
			
               $date = test_input($_POST["date"]);
			    $cno = test_input($_POST["conno"]);
			   
            }
			function test_input($data) {
            $data = trim($data);
            $data = stripslashes($data);
            $data = htmlspecialchars($data);
            return $data;
         }
 ?>
<html>
<head>
<title>Electric Board Online Payment</title>
<link rel="icon" href="logo.png" type="image/png">
<meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
</head>
<style>
.navbar-nav{
	margin-left:auto;
}
.dash
{
	padding:10px;
	background-color:white;
}
.center
{
	display: flex;
  justify-content: center;
  align-items: center;
  height: 100px;
  
}
input[type=submit] {
  background-color:#f23b3b;
  color: white;
  position: 10px 100 px;
  padding: 10px 20px;
  border: none;
  border-radius: 4px;
  
}

#head1{
	background-color:red;
	color:black;
}
table, td, th {
  border: 2px solid black;
  margin-top:50px;
  margin-left:100px;
}

table {
	color:black;
  border-collapse: collapse;
  width: 70%;
}
.jumbotron {
background-color:white;
  margin: 10px auto;
  height:100%;
  justify-content: center;

 // border: 0.08em solid black;
}

.bg-cover {
    background-attachment: static;
    background-position: center;
    background-repeat: no-repeat;
    background-size: cover;
}
#dat {
  background-color:#f23b3b;
  color: white;
  position: 10px 100 px;
  padding: 10px 20px;
  border: none;
  border-radius: 4px;
}
.button-container-div {
            text-align: center;
        }
</style>
<body>
<nav class="navbar navbar-expand-sm bg-dark">
<a class="navbar-brand" href="#">
<img src="logo.png" alt="" style="width:45px">
</a>
<h2 style="color:white">Electric Bill<br>
 Generation System</h2>
 <ul class="navbar-nav">
    <li class="nav-item">
      <a class="nav-link" style="color:white" href="adminarchieve.php">Bill Archieve</a>
    </li>
    <li class="nav-item">
      <a class="nav-link" style="color:white" href="Logout.php">LOGOUT</a>
    </li>
    <li class="nav-item">
      <a class="nav-link" style="color:white" href="#"><?php echo $_SESSION["adminname"] ?></a>
	  
    </li>
  </ul>
</nav>
<p style="color:#2545c1;text-align:center"><b>*Pay early to avoid unexpected network / connectivity issues on the last date</b></p>
<div class="jumbotron bg-cover" style="width:50%">
<div style="padding:5px;color:white">
<h6 style="color:white;text-align:center;background-color:red"><b><?php echo $cno ?> </b> 's Bill at <b><?php echo $date; ?> </b>.</h6>
</div >
<div style="padding:5px;color:black;background-color:#4791e3">
<h1 style="color:white;text-align:center"><font face = "WildWest" >Invoice</font></h1>
<p style="text-align:right;font-family: Times New Roman, Times, serif;color:white">Generated By : Electric Bill Generation System</p>

</div><br>
<?php
$con=mysqli_connect("localhost","Projectphp","php123!@#","electricbillgeneration");
$query="SELECT * from bill_payed where Date='{$date}' && consumer_no='{$cno}'";
$result=mysqli_query($con,$query);
if(mysqli_num_rows($result)>0)
{
	while($row=mysqli_fetch_assoc($result))
	{
		$amount=$row["Amount"];
		$units=$row["units"];
		echo '<b>Service Number  : </b> '.$cno.'&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp';
		echo '<b>Amount Paid  :  </b> '.$amount;
		echo '<hr style="border: 2px solid blue;
  border-radius: 5px;">';
		echo '<b>Units Consumed  :  </b> '.$units.'&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp;';
		echo '<b>Date  :  </b> '.$date.'<br><br>';
		echo '<hr style="border: 2px solid blue;
  border-radius: 5px;">';
	}
	echo '<div class="button-container-div">
<button onclick=window.print() id="dat" ><i class="fa fa-print"></i> Print</button>
</div>';
	
}
else
{
	 echo '<p> No payments Done</p>';
}		 
?>



</div>


</body>
</html>